apiVersion: v1
kind: Pod
metadata:
  name: my-secrete-pod
spec:
  containers:
  - name: my-container
    image: mlrene/sample-repo:1.0
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/secret-volume"
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret
imagePullSecrets:
  - name: myregistrykey    
